sudo: false
language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-5.0
    packages:
    - clang-5.0
install:
- "[ $CXX = clang++ ] && export CXX=clang++-5.0 || true"
script:
  - echo "build for desktop"
  - cd platforms/desktop
  - mkdir -p build
  - cd build
  - cmake ..
  - make -j4


